added arrow dowm svg to dropdowns fixes #47
berkeley-homes/near-miss-positive-intervention pull request #77
Opened 2017-04-05 15:38 UTC by nogainbar

Also added max-width to the whole of form container so that it doesnt stretch of larger screens

2017-04-11 11:40 UTC, jbesraa approved these changes

2017-04-11 11:41 UTC, jbesraa requested changes
please fix merge conflicts

2017-04-11 19:00 UTC, des-des requested changes

2017-04-11 19:00 UTC, des-des commented on public/style.css
> +  max-width: 330px;
Yeah guessing this is for website on desktop, we can use tachyons as this has media queries if we want

2017-04-11 19:01 UTC, des-des commented
@esraajb okay I am gonna focus on getting the email stuff working, do you want to make that change?

2017-04-12 10:10 UTC, jbesraa approved these changes

2017-04-12 10:17 UTC, esraajb commented
@des-des

2017-04-12 11:39 UTC, des-des approved these changes

2017-04-12 11:39 UTC, merged