add header
berkeley-homes/near-miss-positive-intervention pull request #80
Opened 2017-04-11 09:50 UTC by esraajb

related to #75
add header and header tests

2017-04-11 19:08 UTC, des-des requested changes

2017-04-11 19:08 UTC, des-des commented on public/img/Burger_menu.svg
> +<?xml version="1.0" encoding="UTF-8"?>
can we change the name of this file so that it starts with a lower case letter

2017-04-11 19:08 UTC, des-des commented on public/img/NearMiss_nav_logo.svg
> +<?xml version="1.0" encoding="UTF-8"?>
Same here, lower case only for file names

2017-04-11 19:08 UTC, des-des commented on public/style.css
> +  height:100%;
What does this do?

2017-04-11 19:08 UTC, des-des commented on public/style.css
> +  line-height: 0.8;
What is this for?

2017-04-11 19:08 UTC, des-des commented on public/style.css
> +body{
what does this do?

2017-04-11 19:08 UTC, des-des commented on public/style.css
> +  padding-left:2.5em;
Why can't we use tachyons?

2017-04-11 19:08 UTC, des-des commented on public/style.css
> +  padding-right:1.5rem;
And here

2017-04-11 19:08 UTC, des-des commented on public/style.css
> +/*revisit after merging nogas PRs*/
This pr is assigned to me, is it ready to merge?

2017-04-11 19:08 UTC, des-des commented on public/style.css
> +  height: 50px;
pls do we need px?

2017-04-11 19:08 UTC, des-des commented on public/style.css
> +  height: 32px;
here

2017-04-11 19:08 UTC, des-des commented on public/style.css
> +  height: 108px;
here

2017-04-11 19:08 UTC, des-des commented on public/style.css
> +.divi {
Why is this in the pull? I thought it was for the spinner? Also I think it has been deleted

2017-04-11 19:08 UTC, des-des commented on src/client/components/header.js
> +class Header extends Component {
We need to make a stylistic decision.

I have been using pure components, but you have been using the class syntax.

We need to choose one or the other

2017-04-11 19:08 UTC, des-des commented on test/client/components/header.js
> +  t.plan(3)
t.plan I do not think we want this

2017-04-12 06:41 UTC, esraajb commented on public/style.css
> +/*revisit after merging nogas PRs*/
Its ready. the comments are for me to do when we merge nogas PRs and mine. I dont wanna clean the css file before knowing why things are written in it

2017-04-12 06:42 UTC, esraajb commented on public/style.css
> +  height: 50px;
I dont use this. will clean the file after merging in nogas and my PRs

2017-04-12 06:43 UTC, esraajb commented on public/style.css
> +  height: 32px;
I dont use this. will clean the file after merging in nogas and my PRs

2017-04-12 06:43 UTC, esraajb commented on public/style.css
> +  height: 108px;
I dont use this. will clean the file after merging in nogas and my PRs

2017-04-12 06:43 UTC, esraajb commented on public/style.css
> +.divi {
Its on master. andd
I dont use this. will clean the file after merging in nogas and my PRs

2017-04-12 14:23 UTC, esraajb commented on test/client/components/header.js
> +  t.plan(3)
why not ?

2017-04-12 14:35 UTC, esraajb commented
@des-des Header(tachyons only) is ready to be merged. 
Another file name editing/code cleaning/tests... will be done in another branch

2017-04-12 15:24 UTC, des-des requested changes
coolio jus a couple of small things

2017-04-12 15:24 UTC, des-des commented on public/img/Burger_menu.svg
> +<?xml version="1.0" encoding="UTF-8"?>
@esraajb This still needs doing

2017-04-12 15:24 UTC, des-des commented on public/img/NearMiss_nav_logo.svg
> +<?xml version="1.0" encoding="UTF-8"?>
and this

2017-04-12 15:24 UTC, des-des commented on test/client/components/header.js
> +  t.plan(3)
you are calling `t.end()` when your tests are done. `t.plan` is not for this use case, mostly it is useful for async stuff

2017-04-12 15:26 UTC, des-des commented
@esraajb lookin good, not sure I understand your comment. Jus two things left

2017-04-12 15:32 UTC, esraajb commented
@des-des done

2017-04-13 09:46 UTC, des-des approved these changes

2017-04-13 09:46 UTC, merged