add thumbs page
berkeley-homes/near-miss-positive-intervention pull request #81
Opened 2017-04-11 10:09 UTC by esraajb

related to 64#
add thumbs components
add thumbs container
add tests to thumbs

2017-04-11 19:17 UTC, des-des requested changes

2017-04-11 19:17 UTC, des-des commented on public/style.css
> +.center_img{
This is the same as 
`center db` in tachyons

2017-04-11 19:17 UTC, des-des commented on public/style.css
> +.center_img{
If you do a search for `.center` and `.db` [here](http://tachyons.io/docs/table-of-styles/) you can see its identical

2017-04-11 19:17 UTC, des-des commented on src/client/components/thumbs_up.js
> +class ThumbsUpBtn extends Component {
I think button is the wrong name. Just call it `ThumbsUp`.

2017-04-11 19:17 UTC, des-des commented on src/client/containers/thumbs.js
> +import ThumbsDownBtn from '../components/thumbs_down.js'
Again, these are not buttons

2017-04-11 19:17 UTC, des-des commented on test/client/components/thumbs_down.js
> +import ThumbsDownBtn from '../../../src/client/components/thumbs_down.js'
name here also

2017-04-11 19:17 UTC, des-des commented on test/client/components/thumbs_down.js
> +  t.plan(2)
:fire: `t.plan`

2017-04-11 19:17 UTC, des-des commented on test/client/components/thumbs_up.js
> +import ThumbsUpBtn from '../../../src/client/components/thumbs_up.js'
name

2017-04-11 19:17 UTC, des-des commented on test/client/components/thumbs_up.js
> +  t.plan(2)
:fire:

2017-04-12 06:34 UTC, esraajb commented
@des-des fixed

2017-04-12 08:57 UTC, des-des approved these changes

2017-04-12 08:57 UTC, merged